server:
  port: 8080
#  工厂方法模式 FactoryMethodPattern
#  简单工厂模式 SimpleFactoryPattern
#  抽象工厂模式 AbstractFactoryPattern
#  单例模式 SingletonPattern
#  原型模式 PrototypePattern
#  建造者模式 BuilderPattern
#  外观模式 FacadePattern
#  适配器模式 AdapterPattern
#  桥接模式 BridgePattern
#  组合模式 CompositePattern
#  修饰器模式 DecoratorPattern
#  代理模式 ProxyPattern
#  享元模式 FlyweightPattern
#  模板模式 TemplatePattern
#  策略模式 StrategyPattern
pattern: StrategyPattern