server:
  port: 8080
#  工厂方法模式 FactoryMethodPattern
#  简单工厂模式 SimpleFactoryPattern
#  抽象工厂模式 AbstractFactoryPattern
#  单例模式 SingletonPattern
#  原型模式 PrototypePattern
#  建造者模式 BuilderPattern
#  外观模式 FacadePattern
#  适配器模式 AdapterPattern
#  桥接模式 BridgePattern
#  组合模式 CompositePattern
#  修饰器模式 DecoratorPattern
#  代理模式 ProxyPattern
#  享元模式 FlyweightPattern
#  模板模式 TemplatePattern
#  策略模式 StrategyPattern
#  状态模式 StatePattern
#  责任链模式 ChainOfResponsibilityPattern
#  命令模式 CommandPattern
#  观察者模式 ObserverPattern
#  中介者模式 MediatorPattern
#  迭代器模式 IteratorPattern *因过于简单，故未作实现
#  访问者模式 VisitorPattern
#  备忘录模式 MementoPattern
#  解释器模式 MementoPattern *存在正则表达式这种显而易见的例子，故未作实现
pattern: MementoPattern